# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a366b5f3f2d65cc008fd243e1d421c2ddb3d7be16892be4fa6238a0fc644a89a3d76775578da29b1b65e92459dfbc75dbd9324b8489f7a62e6aaf91a0e0ff14

test:
  secret_key_base: 34752178dcd651feea782780bf3a7ac1d487f96af711e06b4dd255984a828ee1b3e6b2ecd0cb9eebcc377ce83a52b0dc9e5f51401ee06bd44a1fd1176ebdef4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
